[global]
pid = /var/run/php-fpm.pid
error_log = /dev/fd/2
process_control_timeout = ${FPM_PROCESS_CONTROL_TIMEOUT}

[www]
user  = ${USER}
group = ${USER}

listen         = [::]:9000
listen.owner   = ${USER}
listen.group   = ${USER}
listen.backlog = 65535

pm                      = ondemand
pm.max_children         = ${FPM_PM_MAX_CHILDREN}
pm.process_idle_timeout = ${FPM_PM_PROCESS_IDLE_TIMEOUT}
pm.max_requests         = ${FPM_PM_MAX_REQUESTS}
pm.status_path          = /status

include = ${PHP_ENV_FILE}
